name: 🐛 Bug Report
description: Report a problem or unexpected behavior
title: "[Bug] "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: input
    id: device
    attributes:
      label: Device Model
      description: Which iPhone model are you using?
      placeholder: e.g., iPhone 13 Pro
    validations:
      required: true

  - type: input
    id: ios_version
    attributes:
      label: iOS Version
      description: Which iOS version are you running?
      placeholder: e.g., iOS 17.2
    validations:
      required: true

  - type: input
    id: app_version
    attributes:
      label: App Version
      description: Which version of Mogu Exercise?
      placeholder: e.g., 1.0.0 (check in Settings)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
      placeholder: What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: The app should...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, this happened...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Drag and drop screenshots here

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem (e.g., error messages, console logs)
      placeholder: Add any other context about the problem here.

  - type: markdown
    attributes:
      value: |
        ---
        **Privacy Note**: Please don't include any personal information or sensitive data in your bug report.
